version: '2'
services:
  database:
    image: postgres
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  todo:
    image: enderdwt/sbt
    environment:
      - DB_URL=jdbc:postgresql://database/postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    volumes:
      - .:/app
      - ~/.ivy2:/root/.ivy2
      